/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package romanos;

import java.awt.Container;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author lis
 */
public class Principal extends javax.swing.JFrame {
Conversor c = new Conversor();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setVisibility(false);
        
        jTPlaceHolder.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent ke) { 
                char cha =ke.getKeyChar(); 
                if(!Character.isDigit(cha)) {
                    getToolkit().beep();
                    ke.consume();  
                }
                if(jTPlaceHolder.getText().length() >3){
                    ke.consume();
                    JOptionPane.showMessageDialog(null,"El numero no puede ser mayor a 1000", "Error", JOptionPane.WARNING_MESSAGE);  
                }
            } 
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIntruccion = new javax.swing.JLabel();
        jTPlaceHolder = new javax.swing.JTextField();
        jBConvertir = new javax.swing.JButton();
        jLResult1 = new javax.swing.JLabel();
        jLresultQuest = new javax.swing.JLabel();
        jLresult2 = new javax.swing.JLabel();
        jLResult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");
        setMinimumSize(new java.awt.Dimension(537, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLIntruccion.setText("Ingrese el numero arabico  que desea convertir a numero romano");
        getContentPane().add(jLIntruccion);
        jLIntruccion.setBounds(10, 10, 415, 15);

        jTPlaceHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPlaceHolderActionPerformed(evt);
            }
        });
        getContentPane().add(jTPlaceHolder);
        jTPlaceHolder.setBounds(10, 70, 370, 25);

        jBConvertir.setText("Convertir");
        jBConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConvertirActionPerformed(evt);
            }
        });
        getContentPane().add(jBConvertir);
        jBConvertir.setBounds(400, 70, 100, 27);

        jLResult1.setText("El numero: ");
        getContentPane().add(jLResult1);
        jLResult1.setBounds(10, 110, 90, 15);

        jLresultQuest.setText("jLabel3");
        getContentPane().add(jLresultQuest);
        jLresultQuest.setBounds(100, 110, 44, 15);

        jLresult2.setText("en numeros romanos es:");
        getContentPane().add(jLresult2);
        jLresult2.setBounds(190, 110, 180, 15);

        jLResult.setText("jLabel5");
        getContentPane().add(jLResult);
        jLResult.setBounds(10, 140, 350, 15);

        jLabel1.setText("Recuerde que solo se pueden ingresar numeros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 410, 15);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPlaceHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPlaceHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPlaceHolderActionPerformed

    
        /**
     * Realizamos las acciones del boton
     */
    private void jBConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConvertirActionPerformed
        // TODO add your handling code here:
        
        String numero = jTPlaceHolder.getText();    //Obtenemos el numero como un txt
        int value = Integer.parseInt(numero);
        if((numero.trim().equals("")) || (1000<value)){               //Comprobamos que el campo no este vacio y restringimos el valor maximo
            JOptionPane.showMessageDialog(null,"El numero no puede ser vacio o mayor a 1000", "Error", JOptionPane.WARNING_MESSAGE);

            return;
        }
        jLresultQuest.setText(numero);                      
        String resultado = c.romanoDe(numero);                  //Obtenemos el Valor del numero a numeros romanos    
         jLResult.setText(resultado);               
         setVisibility(true);                       //ponemos la visibilidad 

    }//GEN-LAST:event_jBConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
        /**
     * Establecemos la visibilidad de los resultados
     */
    
    public void setVisibility(Boolean b){
                jLResult.setVisible(b);
        jLResult1.setVisible(b);
        jLresult2.setVisible(b);
        jLresultQuest.setVisible(b);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConvertir;
    private javax.swing.JLabel jLIntruccion;
    private javax.swing.JLabel jLResult;
    private javax.swing.JLabel jLResult1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLresult2;
    private javax.swing.JLabel jLresultQuest;
    private javax.swing.JTextField jTPlaceHolder;
    // End of variables declaration//GEN-END:variables
}
